---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/output2/output2.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/867133/articles/1247566/master/file/figures/output2/output2.png"
