---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Mask R-CNN/Mask R-CNN.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/867133/articles/1247566/master/file/figures/Mask%20R-CNN/Mask%20R-CNN.png"
